/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_itheima_demo01var_Hellowrold */

#ifndef _Included_com_itheima_demo01var_Hellowrold
#define _Included_com_itheima_demo01var_Hellowrold
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_itheima_demo01var_Hellowrold
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_itheima_demo01var_Hellowrold_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
